#!/usr/bin/env python3
"""Generate seed_data/*.json files with educational content for all topics."""

import json, os, sys

DATA_DIR = os.path.join(os.path.dirname(__file__), "seed_data")
os.makedirs(DATA_DIR, exist_ok=True)

def write_json(filename, data):
    path = os.path.join(DATA_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Wrote {path} ({os.path.getsize(path)} bytes)")


# ============================================================
# MATH: Chapter 4 - Quadratic Equations
# ============================================================

def math_ch4():
    return {
        "312b176c04218525": {
            "summary": "Solving quadratic equations by factorization involves expressing ax² + bx + c = 0 as a product of two linear factors, then setting each factor to zero. This method is the quickest when the quadratic expression can be easily factorized. The key is finding two numbers whose sum equals b and product equals ac.",
            "chunks": [
                {
                    "title": "Solution of a Quadratic Equation by Factorisation",
                    "content": "The **factorisation method** is one of the simplest and most commonly used techniques for solving quadratic equations. It relies on the **zero product property**: if p × q = 0, then either p = 0 or q = 0.\n\n**Steps for solving by factorisation:**\n\n**Step 1:** Write the equation in standard form: ax² + bx + c = 0\n\n**Step 2:** Factor the quadratic expression on the left-hand side.\n   To factor ax² + bx + c:\n   - Find two numbers whose sum = b and product = ac\n   - Split the middle term using these numbers\n   - Group and factor\n\n**Step 3:** Set each factor equal to zero and solve for x.\n\n**Example 1:** Solve x² - 5x + 6 = 0\n   Find numbers with sum = -5 and product = 6: -2 and -3\n   x² - 2x - 3x + 6 = 0\n   x(x - 2) - 3(x - 2) = 0\n   (x - 2)(x - 3) = 0\n   x = 2 or x = 3\n\n**Example 2:** Solve 2x² - 5x + 3 = 0\n   Find numbers with sum = -5 and product = 2×3 = 6: -2 and -3\n   2x² - 2x - 3x + 3 = 0\n   2x(x - 1) - 3(x - 1) = 0\n   (x - 1)(2x - 3) = 0\n   x = 1 or x = 3/2\n\nThe factorisation method works only when the quadratic expression can be factorised over integers. When it cannot, other methods like completing the square or the quadratic formula must be used."
                },
                {
                    "title": "Key Steps and Examples of Factorisation",
                    "content": "**1. General Technique for Factorisation:**\n   For ax² + bx + c = 0:\n   - Find two numbers p and q such that p + q = b and p × q = ac\n   - Rewrite as ax² + px + qx + c = 0\n   - Factor by grouping:\n     * First two terms: common factor\n     * Last two terms: common factor\n   - Take common binomial factor\n\n**2. Special Cases:**\n\n   **Case 1: When a = 1**\n   x² + bx + c = (x + p)(x + q) where p + q = b and pq = c\n   Example: x² - 7x + 12 = (x - 3)(x - 4) ✓\n\n   **Case 2: Perfect square trinomial**\n   x² + 2px + p² = (x + p)²\n   Example: x² + 6x + 9 = (x + 3)²\n\n   **Case 3: Difference of squares**\n   x² - p² = (x - p)(x + p)\n   Example: x² - 16 = (x - 4)(x + 4)\n\n**3. Examples with one variable substitution:**\n   Sometimes equations can be reduced to quadratic form:\n   Example: Solve x⁴ - 5x² + 4 = 0\n   Let y = x²: y² - 5y + 4 = 0 → (y-1)(y-4) = 0\n   y = 1 or y = 4 → x² = 1 or x² = 4 → x = ±1 or x = ±2\n\n**4. Example with word problem leading to factorisation:**\n   The product of two consecutive positive integers is 132. Find them.\n   Let integers be x and x+1.\n   x(x+1) = 132 → x² + x - 132 = 0 → (x+12)(x-11) = 0\n   x = 11 or x = -12 (reject negative)\n   Integers are 11 and 12. Check: 11 × 12 = 132 ✓"
                },
                {
                    "title": "Worked Example: Solving by Factorisation",
                    "content": "**Problem:** Solve 3x² - 4x - 4 = 0 by factorisation.\n\n**Solution:**\n\n**Step 1:** Identify a, b, c.\na = 3, b = -4, c = -4\n\n**Step 2:** Find two numbers whose sum = b = -4 and product = ac = 3(-4) = -12.\nFactors of -12: (-1, 12), (1, -12), (-2, 6), (2, -6), (-3, 4), (3, -4)\nCheck sums: -1+12=11 ✗, 1+(-12)=-11 ✗, -2+6=4 ✗, 2+(-6)=-4 ✓\nNumbers: 2 and -6\n\n**Step 3:** Split the middle term.\n3x² + 2x - 6x - 4 = 0\n\n**Step 4:** Factor by grouping.\nGroup 1: 3x² + 2x = x(3x + 2)\nGroup 2: -6x - 4 = -2(3x + 2)\n\n**Step 5:** Take common factor (3x + 2).\n(3x + 2)(x - 2) = 0\n\n**Step 6:** Set each factor to zero.\n3x + 2 = 0 → x = -2/3\nx - 2 = 0 → x = 2\n\n**Solution: x = -2/3 or x = 2**\n\n**Verification:**\nFor x = 2: 3(4) - 4(2) - 4 = 12 - 8 - 4 = 0 ✓\nFor x = -2/3: 3(4/9) - 4(-2/3) - 4 = 4/3 + 8/3 - 4 = 12/3 - 4 = 0 ✓\n\n---\n\n**Problem 2:** Solve 4x² + 4√3x + 3 = 0\nNumbers with sum = 4√3 and product = 4×3 = 12: 2√3 and 2√3\n4x² + 2√3x + 2√3x + 3 = 0\n2x(2x + √3) + √3(2x + √3) = 0\n(2x + √3)(2x + √3) = 0\nx = -√3/2 (repeated root)"
                },
                {
                    "title": "Common Mistakes and Tips for Factorisation",
                    "content": "**Common Mistakes:**\n\n❌ **Wrong sign selection:** When finding p and q such that p+q=b and pq=ac, pay careful attention to signs. If ac is positive and b is positive, both p and q are positive. If ac is positive and b is negative, both p and q are negative.\n\n❌ **Forgetting the a coefficient:** When factorising ax² + bx + c with a ≠ 1, the factors will not simply be (x + p)(x + q). Use the splitting method or the cross-multiplication method.\n\n❌ **Stopping after one factor:** If (x - 2)(2x - 1) = 0, you need to solve BOTH x - 2 = 0 (giving x = 2) AND 2x - 1 = 0 (giving x = 1/2).\n\n❌ **Not writing in standard form:** Always rearrange to ax² + bx + c = 0 first. Equations like x² = 5x must become x² - 5x = 0.\n\n**Tips and Tricks:**\n\n✓ **Quick check:** After factorising, expand your factors to verify they give the original expression.\n\n✓ **Common factor first:** Always check if there is a common factor in all terms before factorising.\nExample: 2x² - 8x + 6 = 2(x² - 4x + 3) = 2(x-1)(x-3)\n\n✓ **Perfect square test:** Check if b² = 4ac. If so, the quadratic is a perfect square: (√a·x ± √c)².\n\n✓ **Zero product property:** If the constant term c = 0, the equation is x(ax + b) = 0 with roots x = 0 and x = -b/a."
                },
                {
                    "title": "Practice Problems on Factorisation",
                    "content": "**Problem 1 (Basic):**\nSolve: x² - 9x + 20 = 0\n\n**Answer:** (x - 4)(x - 5) = 0 → x = 4 or x = 5. Verify: 16-36+20=0 ✓, 25-45+20=0 ✓.\n\n---\n\n**Problem 2 (Intermediate):**\nSolve: 6x² + x - 2 = 0\n\n**Answer:** Numbers with sum=1, product=-12: 4 and -3. 6x² + 4x - 3x - 2 = 2x(3x+2) - 1(3x+2) = (3x+2)(2x-1) = 0. x = -2/3 or x = 1/2.\n\n---\n\n**Problem 3 (Advanced):**\nSolve: (x - 3)(x - 4) = 34/(33)² (difficult) — Try simpler: Solve 9x² - 9(a+b)x + (2a² + 5ab + 2b²) = 0\n\n**Answer:** Splitting: 9x² - 9(a+b)x + (2a²+5ab+2b²) = 0. ac = 9(2a²+5ab+2b²) = 18a²+45ab+18b². Need p+q = -9(a+b), pq = 18a²+45ab+18b² = (6a+3b)(3a+6b) = 3(2a+b)·3(a+2b) = 9(2a+b)(a+2b). Numbers: -3(2a+b) and -3(a+2b) since sum = -9a-9b = -9(a+b) ✓. So 9x² - 3(2a+b)x - 3(a+2b)x + (2a²+5ab+2b²) = 3x(3x-(2a+b)) - (a+2b)(3x-(2a+b)) = (3x-(2a+b))(3x-(a+2b)) = 0. x = (2a+b)/3 or x = (a+2b)/3."
                }
            ]
        },
        "a20699da6b5c6858": {
            "summary": "The method of completing the square transforms ax² + bx + c = 0 into (x + p)² = q by adding (b/2a)² to both sides. This systematic approach always works and leads to the quadratic formula. It is also useful for finding the vertex of a parabola and solving optimization problems.",
            "chunks": [
                {
                    "title": "Solution of a Quadratic Equation by Completing the Square",
                    "content": "The **method of completing the square** is an algebraic technique that transforms any quadratic equation into a perfect square trinomial plus a constant. This method is especially useful when factorisation is not possible or convenient.\n\n**The key idea:** A perfect square trinomial has the form x² + 2px + p² = (x + p)². Given x² + bx, we can create a perfect square by adding and subtracting (b/2)².\n\n**Steps for solving ax² + bx + c = 0:**\n\n**Step 1:** Divide by a (if a ≠ 1): x² + (b/a)x + c/a = 0\n**Step 2:** Move constant to RHS: x² + (b/a)x = -c/a\n**Step 3:** Add (b/2a)² to both sides: x² + (b/a)x + (b/2a)² = -c/a + (b/2a)²\n**Step 4:** Write LHS as perfect square: (x + b/2a)² = (b² - 4ac)/4a²\n**Step 5:** Take square root: x + b/2a = ±√(b² - 4ac)/2a\n**Step 6:** Solve for x: x = [-b ± √(b² - 4ac)]/2a\n\n**Historical note:** This method dates back to ancient Babylonian mathematics (c. 2000 BCE) and was later formalized by Islamic mathematician Al-Khwarizmi in his 9th-century work 'Al-Kitab al-Mukhtasar fi Hisab al-Jabr wal-Muqabala'."
                },
                {
                    "title": "Applications of Completing the Square",
                    "content": "**1. Solving Quadratic Equations:**\n   The primary use — solving equations that cannot be factorised easily.\n\n**2. Deriving the Quadratic Formula:**\n   Completing the square on ax² + bx + c = 0 gives x = [-b ± √(b² - 4ac)]/2a.\n\n**3. Finding the Vertex of a Parabola:**\n   y = ax² + bx + c can be written as y = a(x - h)² + k, where:\n   - h = -b/2a (x-coordinate of vertex)\n   - k = c - b²/4a (y-coordinate of vertex)\n   This is called the **vertex form**.\n   Example: y = x² - 6x + 11 = (x - 3)² + 2, vertex at (3, 2).\n\n**4. Finding Maximum/Minimum Values:**\n   Since (x - h)² ≥ 0, the minimum value of a(x - h)² + k is k (if a > 0) or maximum if a < 0.\n   Example: Minimum of y = 2x² - 8x + 9: = 2(x² - 4x) + 9 = 2[(x-2)² - 4] + 9 = 2(x-2)² + 1. Minimum = 1 at x = 2.\n\n**5. Graphing Parabolas:**\n   Vertex form immediately gives:\n   - Vertex: (h, k)\n   - Axis of symmetry: x = h\n   - Direction: upward if a > 0, downward if a < 0\n\n**6. Solving Real-World Problems:**\n   - Projectile motion: h(t) = -16t² + v₀t + h₀, find maximum height by completing the square.\n   - Optimization: find dimensions that maximize area given fixed perimeter."
                },
                {
                    "title": "Worked Example: Completing the Square Method",
                    "content": "**Problem:** Solve 2x² - 7x + 3 = 0 by completing the square.\n\n**Solution:**\n\n**Step 1:** Divide by 2.\nx² - (7/2)x + 3/2 = 0\n\n**Step 2:** Move constant to RHS.\nx² - (7/2)x = -3/2\n\n**Step 3:** Add (half coefficient of x)² to both sides.\nCoefficient of x = -7/2. Half = -7/4. Square = 49/16.\nx² - (7/2)x + 49/16 = -3/2 + 49/16\n\n**Step 4:** Simplify RHS.\n-3/2 = -24/16\nRHS = -24/16 + 49/16 = 25/16\n\n**Step 5:** Write LHS as perfect square.\n(x - 7/4)² = 25/16\n\n**Step 6:** Take square root.\nx - 7/4 = ±√(25/16) = ±5/4\n\n**Step 7:** Solve for x.\nx = 7/4 ± 5/4\nx = 7/4 + 5/4 = 12/4 = 3\nx = 7/4 - 5/4 = 2/4 = 1/2\n\n**Solution: x = 3 or x = 1/2**\n\n**Verification:**\nFor x = 3: 2(9) - 7(3) + 3 = 18 - 21 + 3 = 0 ✓\nFor x = 1/2: 2(1/4) - 7(1/2) + 3 = 1/2 - 7/2 + 3 = -3 + 3 = 0 ✓"
                },
                {
                    "title": "Common Mistakes and Tips for Completing the Square",
                    "content": "**Common Mistakes:**\n\n❌ **Forgetting to divide by a first:** If a ≠ 1, you must divide the WHOLE equation by a before completing the square. Otherwise the algebra breaks down.\n\n❌ **Adding (b/2)² instead of (b/2a)²:** After dividing by a, the x coefficient is b/a, so you add (b/2a)².\n\n❌ **Sign error when taking square root:** Remember: √(25/16) = ±5/4, not just 5/4. The ± gives both roots.\n\n❌ **Only adding to one side:** Whatever you add to the LHS must also be added to the RHS to maintain equality.\n\n**Tips and Tricks:**\n\n✓ **Check if b is even:** If b is even, completing the square is cleaner since (b/2)² is an integer.\n\n✓ **Quick vertex formula:** h = -b/(2a), k = f(h). Just evaluate the original function at x = -b/(2a).\n\n✓ **Shortcut when a = 1:** x² + bx = -c → x² + bx + (b/2)² = -c + (b/2)² → (x + b/2)² = (b² - 4c)/4\n\n✓ **Verification:** Expand (x + p)² + q to check it matches the original expression."
                },
                {
                    "title": "Practice Problems on Completing the Square",
                    "content": "**Problem 1 (Basic):**\nSolve x² + 8x - 9 = 0 by completing the square.\n\n**Answer:** x² + 8x = 9 → x² + 8x + 16 = 9 + 16 → (x + 4)² = 25 → x + 4 = ±5 → x = 1 or x = -9.\n\n---\n\n**Problem 2 (Intermediate):**\nSolve 4x² - 4x + 1 = 0 by completing the square.\n\n**Answer:** Divide by 4: x² - x + 1/4 = 0 → x² - x = -1/4 → x² - x + 1/4 = -1/4 + 1/4 → (x - 1/2)² = 0 → x = 1/2 (repeated root). Check: 4(1/4) - 4(1/2) + 1 = 1 - 2 + 1 = 0 ✓.\n\n---\n\n**Problem 3 (Advanced):**\nExpress y = 3x² - 12x + 7 in vertex form and find its minimum value.\n\n**Answer:** y = 3(x² - 4x) + 7 = 3[(x - 2)² - 4] + 7 = 3(x - 2)² - 12 + 7 = 3(x - 2)² - 5. Vertex: (2, -5). Since a = 3 > 0, parabola opens upward. Minimum value = -5 at x = 2."
                }
            ]
        },
        "a95b5145102aa4c0": {
            "summary": "The nature of roots of a quadratic equation ax² + bx + c = 0 is determined by the discriminant D = b² - 4ac. If D > 0, there are two distinct real roots; if D = 0, there is one repeated real root; if D < 0, there are no real roots. The discriminant also tells us whether the roots are rational or irrational, and whether factorisation is possible.",
            "chunks": [
                {
                    "title": "Nature of Roots of a Quadratic Equation",
                    "content": "The **nature of roots** of a quadratic equation ax² + bx + c = 0 (a ≠ 0) is determined entirely by its **discriminant** (D), which is the expression under the square root in the quadratic formula:\n\n**D = b² - 4ac**\n\nThe discriminant gives three cases:\n\n**Case 1: D > 0 (Two distinct real roots)**\n   Roots: x = (-b + √D)/2a and x = (-b - √D)/2a\n   - If D is a perfect square, roots are rational\n   - If D is not a perfect square, roots are irrational (conjugate surds)\n   - The quadratic intersects the x-axis at two distinct points\n\n**Case 2: D = 0 (One repeated real root)**\n   Root: x = -b/2a (both roots are equal)\n   - The quadratic just touches the x-axis (tangent)\n   - The quadratic is a perfect square: a(x + b/2a)²\n\n**Case 3: D < 0 (No real roots)**\n   - Roots are complex conjugates (not in Class X syllabus)\n   - The quadratic does NOT intersect the x-axis\n   - The parabola lies entirely above (if a > 0) or below (if a < 0) the x-axis\n\n**Example 1:** x² - 5x + 6 = 0, D = 25 - 24 = 1 > 0 (perfect square) → Two distinct rational roots: 2 and 3.\n**Example 2:** x² - 6x + 9 = 0, D = 36 - 36 = 0 → One repeated root: 3.\n**Example 3:** 2x² - 4x + 3 = 0, D = 16 - 24 = -8 < 0 → No real roots."
                },
                {
                    "title": "Key Results and Applications of the Discriminant",
                    "content": "**1. Summarising the Nature of Roots:**\n\n| Discriminant | Nature of Roots | Example |\n|-------------|-----------------|---------|\n| D > 0 and perfect square | Real, distinct, rational | x² - 3x + 2 = 0 (D=1) |\n| D > 0 and not perfect square | Real, distinct, irrational | x² - 4x + 1 = 0 (D=12) |\n| D = 0 | Real and equal | x² - 4x + 4 = 0 (D=0) |\n| D < 0 | No real roots | x² + x + 1 = 0 (D=-3) |\n\n**2. Conditions for Specific Types of Roots:**\n   - **Equal roots:** b² - 4ac = 0\n   - **Rational roots:** D is a perfect square (and a, b, c are rational)\n   - **Irrational roots:** D > 0 but not a perfect square\n   - **Real roots:** b² - 4ac ≥ 0\n\n**3. Application Problems:**\n   **Type A — Find k for equal roots:**\n   For kx² - 5x + k = 0 to have equal roots:\n   D = 25 - 4k² = 0 → k² = 25/4 → k = ±5/2\n\n   **Type B — Find k for real roots:**\n   For 3x² + 2x + k = 0 to have real roots:\n   D = 4 - 12k ≥ 0 → k ≤ 1/3\n\n**4. Relationship between Roots and Coefficients (recap):**\n   For ax² + bx + c = 0 with roots α and β:\n   - α + β = -b/a\n   - αβ = c/a\n   - |α - β| = √D/|a|"
                },
                {
                    "title": "Worked Example: Discriminant Problems",
                    "content": "**Problem 1:** Find the value of k for which the equation 2x² + kx + 3 = 0 has equal roots.\n\n**Solution:**\n\n**Step 1:** For equal roots, discriminant D = 0.\nD = b² - 4ac = k² - 4(2)(3) = k² - 24\n\n**Step 2:** Set D = 0.\nk² - 24 = 0\nk² = 24\nk = ±√24 = ±2√6\n\n**Step 3:** The equation has equal roots when k = 2√6 or k = -2√6.\n\nFor k = 2√6: 2x² + 2√6x + 3 = 0 → (√2x + √3)² = 0 → x = -√3/√2\nFor k = -2√6: 2x² - 2√6x + 3 = 0 → (√2x - √3)² = 0 → x = √3/√2\n\n**Problem 2:** Show that the equation x² - 2mx + m² - 1 = 0 always has real roots for any real m.\n\n**Solution:**\nD = (2m)² - 4(1)(m² - 1)\n= 4m² - 4m² + 4\n= 4 > 0 for all real m\n\nSince D > 0 for all m, the equation always has two distinct real roots.\n\nThe roots are: x = [2m ± 2]/2 = m ± 1 → x = m+1, x = m-1"
                },
                {
                    "title": "Common Mistakes and Tips for Nature of Roots",
                    "content": "**Common Mistakes:**\n\n❌ **Confusing D = 0 with 'no roots':** D = 0 means one repeated real root (not 'no root'). D < 0 means no real roots.\n\n❌ **Incorrect sign in discriminant:** D = b² - 4ac, NOT b² + 4ac or b² - 2ac. The formula must be memorised correctly.\n\n❌ **Forgetting that a ≠ 0:** If a = 0, the equation is not quadratic and the discriminant has no meaning.\n\n❌ **Assuming all quadratic equations have real roots:** Many quadratic equations have no real roots (D < 0). Always check the discriminant first.\n\n**Tips and Tricks:**\n\n✓ **Check D first:** Before solving any quadratic, compute D. If D < 0, stop — no real roots.\n\n✓ **Perfect square test:** If D is a perfect square and a, b, c are integers, the roots are rational and factorisation should work.\n\n✓ **Mnemonic:** 'Discriminant tells how many: > 0 means two, = 0 means one, < 0 means none.'\n\n✓ **Quick equal roots check:** For ax² + bx + c = 0 to have equal roots, we need b² = 4ac. This is often called the condition for a perfect square quadratic."
                },
                {
                    "title": "Practice Problems on Nature of Roots",
                    "content": "**Problem 1 (Basic):**\nDetermine the nature of roots of x² - 7x + 10 = 0 without solving.\n\n**Answer:** D = 49 - 40 = 9 > 0 (perfect square). Two distinct rational real roots.\n\n---\n\n**Problem 2 (Intermediate):**\nFind the value of p for which the quadratic equation px² - 6x + 1 = 0 has real and equal roots.\n\n**Answer:** D = 36 - 4p = 0 → 4p = 36 → p = 9. The equation is 9x² - 6x + 1 = (3x - 1)² = 0, root x = 1/3.\n\n---\n\n**Problem 3 (Advanced):**\nIf the roots of the equation (a - b)x² + (b - c)x + (c - a) = 0 are equal, prove that 2a = b + c.\n\n**Answer:** For equal roots, D = 0. (b-c)² - 4(a-b)(c-a) = 0. Expand: b² - 2bc + c² - 4(ac - a² - bc + ab) = 0 → b² - 2bc + c² - 4ac + 4a² + 4bc - 4ab = 0 → b² + 2bc + c² + 4a² - 4ab - 4ac = 0 → (b+c)² - 4a(b+c) + 4a² = 0 → (b+c-2a)² = 0 → 2a = b + c. Hence proved."
                }
            ]
        }
    }


# ============================================================
# MATH: Chapter 5 - Arithmetic Progressions
# ============================================================

def math_ch5():
    return {
        "3982bea92ad68b7a": {
            "summary": "An Arithmetic Progression (AP) is a sequence where each term differs from the previous by a constant called the common difference (d). The general form is a, a+d, a+2d, ... where a is the first term. APs are found throughout nature and daily life — from monthly savings to the pattern of seats in an auditorium.",
            "chunks": [
                {
                    "title": "Introduction to Arithmetic Progressions",
                    "content": "An **Arithmetic Progression (AP)** is a sequence of numbers in which each term (except the first) is obtained by adding a fixed number to the preceding term. This fixed number is called the **common difference**, denoted by d.\n\n**Standard Form:**\na, a + d, a + 2d, a + 3d, ...\nwhere a = first term, d = common difference.\n\n**Examples of APs:**\n   - 2, 5, 8, 11, 14, ... (a = 2, d = 3)\n   - 10, 7, 4, 1, -2, ... (a = 10, d = -3)\n   - 5, 5, 5, 5, ... (a = 5, d = 0 — constant sequence)\n   - -3, -1, 1, 3, ... (a = -3, d = 2)\n\n**Checking if a sequence is an AP:**\nA sequence a₁, a₂, a₃, ... is an AP if a₂ - a₁ = a₃ - a₂ = a₄ - a₃ = ... = d (constant).\n\n**Real-life examples:**\n   - Taxi fare: Rs 15 for first km, Rs 8 for each additional km: 15, 23, 31, 39, ...\n   - Simple interest: Rs 1000 at 10% p.a.: 1000, 1100, 1200, 1300, ...\n   - Number of seats in rows of an auditorium increasing by a fixed number\n\nThe common difference can be positive (increasing AP), negative (decreasing AP), or zero (constant AP)."
                },
                {
                    "title": "Key Terms and Properties of AP",
                    "content": "**1. General Term (nth Term):**\n   aₙ = a + (n - 1)d\n   where n = term number (1-indexed)\n\n**2. Finding d from consecutive terms:**\n   d = a₂ - a₁ = a₃ - a₂ = ...\n   d = (aₘ - aₙ)/(m - n) for any two terms\n\n**3. Finding n given a term's value:**\n   n = (aₙ - a)/d + 1\n\n**4. Arithmetic Mean:**\n   If three numbers are in AP, the middle term is the arithmetic mean of the other two.\n   If a, b, c are in AP: b = (a + c)/2\n\n**5. Selecting terms in AP for problem-solving:**\n   - Three terms: (a - d), a, (a + d) — sum = 3a\n   - Four terms: (a - 3d), (a - d), (a + d), (a + 3d) — sum = 4a\n   - Five terms: (a - 2d), (a - d), a, (a + d), (a + 2d) — sum = 5a\n\n**6. Properties:**\n   - If a constant k is added/subtracted from each term, the new sequence is also an AP with same d.\n   - If each term is multiplied/divided by k (≠ 0), the new sequence is an AP with d multiplied/divided by k.\n   - If two APs have the same number of terms, their sum/difference is also an AP."
                },
                {
                    "title": "Worked Example: Finding Terms of an AP",
                    "content": "**Problem:** Which term of the AP: 3, 8, 13, 18, ... is 78?\n\n**Solution:**\n\n**Step 1:** Identify a and d.\na = 3, d = 8 - 3 = 5\n\n**Step 2:** Use the formula aₙ = a + (n - 1)d.\n78 = 3 + (n - 1)5\n\n**Step 3:** Solve for n.\n78 - 3 = 5(n - 1)\n75 = 5(n - 1)\nn - 1 = 15\nn = 16\n\n**Answer:** The 16th term of the AP is 78.\n\n**Verification:**\na₁₆ = 3 + (16 - 1)5 = 3 + 75 = 78 ✓\n\n---\n\n**Problem 2:** Find the 30th term of the AP: 10, 7, 4, ...\n\n**Solution:**\na = 10, d = 7 - 10 = -3\na₃₀ = 10 + (30 - 1)(-3)\n= 10 + 29(-3)\n= 10 - 87\n= -77\n\n**Answer:** The 30th term is -77.\n\n---\n\n**Problem 3:** Determine whether -150 is a term of the AP: 11, 8, 5, 2, ...\n\n**Solution:**\na = 11, d = 8 - 11 = -3\nLet -150 = aₙ = 11 + (n - 1)(-3)\n-150 - 11 = -3(n - 1)\n-161 = -3(n - 1)\nn - 1 = 161/3 = 53.66...\nn = 54.66... (not an integer)\n\nSince n is not a natural number, -150 is NOT a term of this AP."
                },
                {
                    "title": "Common Mistakes and Tips for AP",
                    "content": "**Common Mistakes:**\n\n❌ **Confusing a and d:** a is the FIRST term, not the second. d = a₂ - a₁, not a₁ - a₂.\n\n❌ **Using aₙ = a + nd:** The correct formula is aₙ = a + (n-1)d. Check: for n=1, a₁ = a + 0·d = a ✓.\n\n❌ **Sign errors with negative d:** When d is negative, aₙ = a + (n-1)(-|d|). Be careful with the signs.\n\n❌ **Not checking if n is a natural number:** When asked 'which term is x?', n must be a positive integer. If you get n = 3.5 or n = -2, x is not a term of the AP.\n\n**Tips and Tricks:**\n\n✓ **Quick verification:** If n=1 gives a, and n=2 gives a+d, you know the formula is correct.\n\n✓ **Common difference from any two terms:** d = (aₘ - aₙ)/(m - n) — no need to know a.\n\n✓ **Three-term trick:** When sum of three numbers in AP is given, take them as (a-d), a, (a+d) and solve for a = sum/3 immediately.\n\n✓ **Graphical interpretation:** An AP is a linear function of n: aₙ = dn + (a - d). Plotting term number vs value gives a straight line."
                },
                {
                    "title": "Practice Problems on Arithmetic Progressions",
                    "content": "**Problem 1 (Basic):**\nFind the 10th term of AP: -5, -1, 3, 7, ...\n\n**Answer:** a = -5, d = 4. a₁₀ = -5 + 9(4) = -5 + 36 = 31.\n\n---\n\n**Problem 2 (Intermediate):**\nThe 5th term of an AP is 11 and the 9th term is 23. Find the AP.\n\n**Answer:** a₅ = a + 4d = 11, a₉ = a + 8d = 23. Subtracting: 4d = 12 → d = 3. a + 12 = 11 → a = -1. AP: -1, 2, 5, 8, 11, ...\n\n---\n\n**Problem 3 (Advanced):**\nFor what value of n are the nth terms of two APs: 63, 65, 67, ... and 3, 10, 17, ... equal?\n\n**Answer:** AP₁: a = 63, d = 2. aₙ = 63 + (n-1)2 = 2n + 61. AP₂: a = 3, d = 7. aₙ = 3 + (n-1)7 = 7n - 4. Set equal: 2n + 61 = 7n - 4 → 5n = 65 → n = 13. Check: AP₁ term = 63+24=87, AP₂ term = 3+84=87 ✓."
                }
            ]
        },
        "b2d85a474854d942": {
            "summary": "The nth term of an AP is given by aₙ = a + (n-1)d, where a is the first term and d is the common difference. This formula allows us to find any term without listing all preceding terms. It is derived from the pattern that each term adds one more d to the first term. The formula is essential for solving problems involving specific terms of APs.",
            "chunks": [
                {
                    "title": "The nth Term of an Arithmetic Progression",
                    "content": "The **nth term** (also called the **general term**) of an AP gives the value of the term at position n without having to list all terms before it. The formula is derived by observing the pattern:\n\n**Derivation:**\n   First term: a₁ = a = a + 0·d\n   Second term: a₂ = a + d = a + 1·d\n   Third term: a₃ = a + 2d = a + 2·d\n   Fourth term: a₄ = a + 3d = a + 3·d\n   ...\n   nth term: aₙ = a + (n - 1)d\n\n**Formula: aₙ = a + (n - 1)d**\n\n**Using the formula to find:**\n   - **A specific term:** Given n, find aₙ\n     Example: Find 15th term of AP 4, 9, 14, ...\n     a = 4, d = 5, a₁₅ = 4 + 14(5) = 4 + 70 = 74\n\n   - **The position of a term:** Given aₙ, find n\n     Example: Which term is 74 in AP 4, 9, 14, ...?\n     74 = 4 + (n-1)5 → 70 = 5(n-1) → n-1 = 14 → n = 15\n\n   - **The first term or common difference:** Given two terms\n     Example: If a₁₀ = 23 and a₂₅ = 53, find a and d.\n     a₁₀ = a + 9d = 23\n     a₂₅ = a + 24d = 53\n     Subtracting: 15d = 30 → d = 2, then a = 23 - 18 = 5"
                },
                {
                    "title": "Applications and Examples of nth Term",
                    "content": "**1. Finding the First Negative Term:**\n   Problem: Which term of AP 20, 17, 14, ... is the first negative term?\n   a = 20, d = -3\n   We need aₙ < 0: 20 + (n-1)(-3) < 0\n   20 - 3n + 3 < 0\n   23 - 3n < 0\n   3n > 23\n   n > 7.67\n   So n = 8. The 8th term is the first negative term.\n   Check: a₈ = 20 + 7(-3) = 20 - 21 = -1 ✓\n\n**2. Finding Number of Terms in an AP:**\n   Problem: How many terms are there in AP 7, 12, 17, ..., 102?\n   a = 7, d = 5, aₙ = 102\n   102 = 7 + (n-1)5\n   95 = 5(n-1)\n   n-1 = 19\n   n = 20 terms\n\n**3. Problem with Fractional Terms:**\n   Problem: Find whether -48 is a term of AP 3, 7, 11, ...\n   a = 3, d = 4\n   -48 = 3 + (n-1)4\n   -51 = 4(n-1)\n   n-1 = -51/4 = -12.75\n   n = -11.75 (not a natural number)\n   Hence -48 is NOT a term.\n\n**4. Two APs with Same Common Difference:**\n   If two APs have the same common difference, the difference between their corresponding terms is constant.\n   Example: AP₁: 2, 5, 8, 11, ... and AP₂: 7, 10, 13, 16, ...\n   Difference: 5, 5, 5, 5, ... (constant)"
                },
                {
                    "title": "Worked Example: Finding nth Term in Context",
                    "content": "**Problem:** In a flower bed, there are 23 rose plants in the first row, 21 in the second, 19 in the third, and so on. There are 5 plants in the last row. How many rows are there?\n\n**Solution:**\n\n**Step 1:** Identify the AP.\nNumber of plants: 23, 21, 19, ..., 5\na = 23, d = 21 - 23 = -2\n\n**Step 2:** Let there be n rows. The last row has 5 plants.\naₙ = a + (n - 1)d = 5\n\n**Step 3:** Substitute values.\n23 + (n - 1)(-2) = 5\n23 - 2n + 2 = 5\n25 - 2n = 5\n-2n = 5 - 25\n-2n = -20\nn = 10\n\n**Step 4:** Verify.\nRow 1: 23\nRow 2: 21\nRow 3: 19\nRow 4: 17\nRow 5: 15\nRow 6: 13\nRow 7: 11\nRow 8: 9\nRow 9: 7\nRow 10: 5 ✓\n\nTherefore, there are **10 rows** of flower beds."
                },
                {
                    "title": "Common Mistakes and Tips for nth Term",
                    "content": "**Common Mistakes:**\n\n❌ **Formula confusion:** aₙ = a + (n-1)d, NOT a + nd. Check: for n = 1, a₁ = a + 0·d = a ✓.\n\n❌ **Wrong substitution:** When finding n, be careful with the order. Write the equation correctly: aₙ = a + (n-1)d.\n\n❌ **Sign errors with subtraction:** If given a₁₅ = 40 and a₁₀ = 25, then a₁₅ - a₁₀ = 5d = 15 → d = 3. Alternatively, (40-25)/(15-10) = 15/5 = 3. ✓\n\n❌ **Not checking n is a natural number:** If solving for n gives a fraction or negative number, the term does not exist in the AP.\n\n**Tips and Tricks:**\n\n✓ **Two-point form:** Given aₘ and aₙ, d = (aₘ - aₙ)/(m - n). This is faster than solving simultaneous equations.\n\n✓ **Alternative representation:** Sometimes written as tₙ = a + (n-1)d instead of aₙ. They mean the same thing.\n\n✓ **Check your answer:** After finding a term, verify by computing a couple of terms manually if the numbers are small.\n\n✓ **Graphical thinking:** Plot term position (n) on x-axis and term value on y-axis. The points lie on a straight line with slope d."
                },
                {
                    "title": "Practice Problems on nth Term of an AP",
                    "content": "**Problem 1 (Basic):**\nFind the 18th term of the AP: 6, 13, 20, 27, ...\n\n**Answer:** a = 6, d = 7. a₁₈ = 6 + 17(7) = 6 + 119 = 125.\n\n---\n\n**Problem 2 (Intermediate):**\nThe 7th term of an AP is 32 and the 13th term is 62. Find the AP.\n\n**Answer:** a + 6d = 32, a + 12d = 62. Subtract: 6d = 30 → d = 5. a = 32 - 30 = 2. AP: 2, 7, 12, 17, ...\n\n---\n\n**Problem 3 (Advanced):**\nThe 4th term of an AP is 0. Prove that the 25th term is three times the 11th term.\n\n**Answer:** a₄ = a + 3d = 0 → a = -3d. a₂₅ = a + 24d = -3d + 24d = 21d. a₁₁ = a + 10d = -3d + 10d = 7d. Since 21d = 3 × 7d, we have a₂₅ = 3 × a₁₁. Hence proved."
                }
            ]
        },
        "a47797bdd2d6dba8": {
            "summary": "The sum of the first n terms of an AP is given by Sₙ = n/2[2a + (n-1)d] = n/2[a + l], where l is the last term. This formula is derived by pairing terms from the beginning and end. It is used in problems involving total savings, seating capacity, and other cumulative quantities.",
            "chunks": [
                {
                    "title": "Sum of First n Terms of an AP",
                    "content": "The **sum of the first n terms** of an AP is a formula that gives the total without adding all terms individually. It was discovered by the famous German mathematician **Carl Friedrich Gauss** when he was just 10 years old.\n\n**Gauss's insight:** To add 1 + 2 + 3 + ... + 100, he paired first and last: 1+100=101, 2+99=101, ..., 50+51=101. There are 50 such pairs, so sum = 50 × 101 = 5050.\n\n**Sum Formulas for an AP:**\n\n**Formula 1:** Sₙ = n/2[2a + (n - 1)d]\n   where n = number of terms, a = first term, d = common difference\n\n**Formula 2:** Sₙ = n/2[a + l]\n   where l = last term = aₙ\n\n**Derivation:**\nLet Sₙ = a + (a+d) + (a+2d) + ... + [a+(n-2)d] + [a+(n-1)d]\nWritten in reverse: Sₙ = [a+(n-1)d] + [a+(n-2)d] + ... + (a+d) + a\nAdding: 2Sₙ = n[2a + (n-1)d]\nSo Sₙ = n/2[2a + (n-1)d]\n\n**Example:** Find sum of first 20 terms of AP 5, 9, 13, 17, ...\na = 5, d = 4, n = 20\nS₂₀ = 20/2[2(5) + (20-1)4] = 10[10 + 76] = 10 × 86 = 860"
                },
                {
                    "title": "Properties and Applications of Sum of n Terms",
                    "content": "**1. Finding Sₙ when a and d are given:**\n   Sₙ = n/2[2a + (n-1)d]\n   Example: Sum of first 15 terms of AP 3, 7, 11, ...\n   a = 3, d = 4, S₁₅ = 15/2[6 + 14(4)] = 15/2[6+56] = 15/2 × 62 = 15 × 31 = 465\n\n**2. Finding Sₙ when a and last term are given:**\n   Sₙ = n/2[a + l]\n   Example: Sum of AP 2, 5, 8, ..., 47 (last term = 47)\n   First find n: 47 = 2 + (n-1)3 → n = 16\n   S₁₆ = 16/2[2 + 47] = 8 × 49 = 392\n\n**3. Finding a given Sₙ:**\n   Since a = S₁, we can find the AP if we know Sₙ.\n   a = S₁, a₂ = S₂ - S₁, a₃ = S₃ - S₂, etc.\n\n**4. Relationship between aₙ and Sₙ:**\n   Sₙ - Sₙ₋₁ = aₙ (the nth term)\n   S₀ = 0 (by convention, sum of zero terms)\n\n**5. Important Results:**\n   - Sₙ = n × (average of first and last term)\n   - Sₙ = n × (mean of the AP) = n × (a + l)/2\n   - If Sₙ is given as a quadratic in n, then d = 2 × coefficient of n²\n\n**6. Real-life application:**\n   A contractor pays Rs 1000 for first day's work, Rs 1100 for second, Rs 1200 for third, continuing. What is the total amount paid for 30 days?\n   a = 1000, d = 100, n = 30\n   S₃₀ = 30/2[2000 + 29(100)] = 15[2000 + 2900] = 15 × 4900 = Rs 73,500"
                },
                {
                    "title": "Worked Example: Problems on Sum of n Terms",
                    "content": "**Problem:** How many terms of the AP: 24, 21, 18, ... must be taken so that their sum is 78?\n\n**Solution:**\n\n**Step 1:** Identify a, d, and Sₙ.\na = 24, d = 21 - 24 = -3, Sₙ = 78\n\n**Step 2:** Use the sum formula.\nSₙ = n/2[2a + (n-1)d]\n78 = n/2[48 + (n-1)(-3)]\n\n**Step 3:** Solve for n.\n78 = n/2[48 - 3n + 3]\n78 = n/2[51 - 3n]\n156 = n(51 - 3n)\n156 = 51n - 3n²\n3n² - 51n + 156 = 0\nn² - 17n + 52 = 0\n(n - 4)(n - 13) = 0\n\n**Step 4:** n = 4 or n = 13.\n\nBoth values are valid!\n- Sum of first 4 terms: 24 + 21 + 18 + 15 = 78 ✓\n- Sum of first 13 terms: Sum first 4 terms (78) + terms 5-13 sum to 0 ✓\n\nCheck terms 5-9: 12, 9, 6, 3, 0, -3, -6, -9, -12 → sum = 0\n\nTherefore, **4 terms or 13 terms** can be taken."
                },
                {
                    "title": "Common Mistakes and Tips for Sum of n Terms",
                    "content": "**Common Mistakes:**\n\n❌ **Using wrong formula:** Sₙ = n/2[2a + (n-1)d], NOT Sₙ = n[a + (n-1)d]. The factor of 1/2 is crucial.\n\n❌ **Confusing n and term value:** n is the number of terms, not the value of the nth term. Sₙ is the sum, not the term.\n\n❌ **Forgetting that S₀ = 0:** The sum of zero terms is always 0. This is a useful check.\n\n❌ **Incorrect use of l = aₙ:** The formula Sₙ = n/2[a + l] requires l = aₙ, NOT aₙ₊₁.\n\n**Tips and Tricks:**\n\n✓ **Quick check:** If n = 1, S₁ should equal a. If n = 2, S₂ should equal a + (a+d) = 2a + d.\n\n✓ **Quadratic form:** Sₙ is always a quadratic function of n. The coefficient of n² is d/2.\n\n✓ **Finding aₙ from Sₙ:** aₙ = Sₙ - Sₙ₋₁. This is a powerful technique when Sₙ is given as a formula.\n\n✓ **Multiple solutions:** When solving for n, expect the possibility of two valid answers (as shown in the example above)."
                },
                {
                    "title": "Practice Problems on Sum of AP",
                    "content": "**Problem 1 (Basic):**\nFind the sum of first 25 terms of AP: 5, 9, 13, 17, ...\n\n**Answer:** a = 5, d = 4. S₂₅ = 25/2[10 + 24(4)] = 25/2[10+96] = 25/2 × 106 = 25 × 53 = 1325.\n\n---\n\n**Problem 2 (Intermediate):**\nIf the sum of first n terms of an AP is 4n - n², find the first term and the common difference.\n\n**Answer:** S₁ = 4(1) - 1² = 3 = a. S₂ = 8 - 4 = 4. a₂ = S₂ - S₁ = 4 - 3 = 1. d = a₂ - a₁ = 1 - 3 = -2. So AP is 3, 1, -1, -3, ...\n\n---\n\n**Problem 3 (Advanced):**\nA spiral is made up of successive semicircles with centres alternately at A and B, starting with centre at A for radii 0.5 cm, 1.0 cm, 1.5 cm, 2.0 cm, ... What is the total length of the spiral made up of 13 consecutive semicircles? (Hint: Length of a semicircle = πr)\n\n**Answer:** Radii: 0.5, 1.0, 1.5, ..., 13×0.5 = 6.5 cm. These form an AP with a = 0.5, d = 0.5, n = 13. Length of each semicircle = πr. Total length = π(0.5 + 1.0 + 1.5 + ... + 6.5) = π × S₁₃. S₁₃ = 13/2[1.0 + 12(0.5)] = 13/2[1.0+6.0] = 13/2 × 7 = 45.5. Total length = 45.5π cm."
                }
            ]
        }
    }


def math_ch6():
    return {
        "5431267dd9267dea": {
            "summary": "Similar figures have the same shape but not necessarily the same size. Two polygons are similar if their corresponding angles are equal and corresponding sides are in the same ratio. For triangles, similarity means the triangles have equal corresponding angles and proportional corresponding sides. Similarity is fundamental to understanding scaling, maps, and models.",
            "chunks": [
                {
                    "title": "Similar Figures",
                    "content": "**Similar figures** are figures that have the same shape but different sizes. Two figures are said to be similar if one can be obtained from the other by a uniform scaling (enlarging or reducing).\n\n**Key properties of similar figures:**\n   - All corresponding angles are equal\n   - All corresponding sides are in the same ratio (called the scale factor)\n\n**Examples of similar figures:**\n   - Any two circles are always similar (same shape, different radii)\n   - Any two squares are always similar (same shape, different side lengths)\n   - Two equilateral triangles are always similar\n   - Two photographs of the same object at different magnifications\n\n**Examples of figures that are NOT necessarily similar:**\n   - Two rectangles may not be similar (different ratios of sides)\n   - Two isosceles triangles may not be similar (different vertex angles)\n\n**Congruence vs Similarity:**\n   - Congruent figures: same shape AND same size (scale factor = 1)\n   - Similar figures: same shape, different sizes (scale factor ≠ 1 typically)\n   - All congruent figures are similar, but not vice versa\n\n**Real-life applications of similarity:**\n   - Maps and scale drawings\n   - Blueprints and architectural models\n   - Photographic enlargements\n   - Shadow measurement for heights"
                },
                {
                    "title": "Properties of Similar Figures",
                    "content": "**1. Ratio of Corresponding Sides:**\n   If two figures are similar, the ratio of any two corresponding sides is constant (the scale factor).\n   Example: If △ABC ∼ △DEF, then AB/DE = BC/EF = CA/FD = k (scale factor)\n\n**2. Ratio of Perimeters:**\n   The ratio of perimeters of two similar figures equals the scale factor.\n   Perimeter(△ABC)/Perimeter(△DEF) = k\n\n**3. Ratio of Areas:**\n   The ratio of areas of two similar figures equals the square of the scale factor.\n   Area(△ABC)/Area(△DEF) = k²\n\n**4. Symmetry of Similarity:**\n   If △ABC ∼ △DEF, then △DEF ∼ △ABC (similarity is symmetric)\n   If △ABC ∼ △DEF and △DEF ∼ △XYZ, then △ABC ∼ △XYZ (similarity is transitive)\n   △ABC ∼ △ABC (reflexive)\n\n**5. Similarity and Proportionality:**\n   If a line is drawn parallel to one side of a triangle, it divides the other two sides proportionally. This is the **Basic Proportionality Theorem (Thales Theorem)**.\n\n**6. Scale Factor Applications:**\n   - If k > 1, the figure is enlarged\n   - If 0 < k < 1, the figure is reduced\n   - If k = 1, the figures are congruent"
                },
                {
                    "title": "Worked Example: Identifying Similar Figures",
                    "content": "**Problem:** Check whether the following pairs of figures are similar:\n(a) A rectangle with sides 4 cm and 6 cm, and another rectangle with sides 8 cm and 12 cm.\n(b) A rhombus with side 5 cm and angle 60°, and another rhombus with side 10 cm and angle 60°.\n\n**Solution:**\n\n**(a) Two rectangles:**\nFor rectangles to be similar, the ratios of corresponding sides must be equal.\nRectangle 1: length = 6 cm, breadth = 4 cm\nRectangle 2: length = 12 cm, breadth = 8 cm\n\nRatio of lengths: 6/12 = 1/2\nRatio of breadths: 4/8 = 1/2\n\nBoth ratios are equal (1/2), and all angles are 90° in both. Therefore, the rectangles are **similar**.\n\n**(b) Two rhombuses:**\nFor rhombuses to be similar, corresponding angles must be equal and corresponding sides proportional.\nBoth have angle 60°, so corresponding angles are equal.\nRatio of sides: 5/10 = 1/2 (constant)\nAll corresponding angles are equal (opposite angles equal, adjacent angles supplementary).\nTherefore, the rhombuses are **similar**.\n\n---\n\n**Problem:** Are all equilateral triangles similar?\n**Answer:** Yes! All equilateral triangles have all angles = 60°. The ratio of any corresponding sides is equal (the triangles may have different side lengths, but the ratio of sides in each triangle is 1:1:1). Therefore, all equilateral triangles are similar."
                },
                {
                    "title": "Common Mistakes and Tips for Similar Figures",
                    "content": "**Common Mistakes:**\n\n❌ **Confusing similarity with congruence:** Similar figures have the same shape; congruent figures have the same shape AND size. Congruence is a special case of similarity with scale factor 1.\n\n❌ **Assuming all rectangles are similar:** Two rectangles are similar only if their length:breadth ratios are equal. A 4×6 rectangle and a 5×10 rectangle are NOT similar (4:6=2:3, 5:10=1:2).\n\n❌ **Wrong correspondence:** When checking similarity, you must correctly identify which sides correspond. Usually, the order of vertices in the notation indicates correspondence.\n\n**Tips and Tricks:**\n\n✓ **Angle check first:** For polygons, if corresponding angles are not equal, the figures cannot be similar. Check angles first before checking sides.\n\n✓ **Scale factor consistency:** If any two pairs of corresponding sides give different ratios, the figures are NOT similar.\n\n✓ **Maps and models:** If a map has scale 1:100,000, then 1 cm on the map represents 1 km on the ground. The map and the actual terrain are similar figures.\n\n✓ **Notation:** Similarity is denoted by the symbol ∼ (tilde). Read △ABC ∼ △DEF as 'triangle ABC is similar to triangle DEF'."
                },
                {
                    "title": "Practice Problems on Similar Figures",
                    "content": "**Problem 1 (Basic):**\nAre all squares similar? Justify.\n\n**Answer:** Yes. All squares have all angles = 90°. The ratio of corresponding sides of any two squares is constant (side₁/side₂). Hence all squares are similar.\n\n---\n\n**Problem 2 (Intermediate):**\nTwo similar triangles have perimeters 30 cm and 45 cm. If a side of the smaller triangle is 8 cm, find the corresponding side of the larger triangle.\n\n**Answer:** Scale factor = ratio of perimeters = 30/45 = 2/3 (smaller:larger). Let larger side = x. 8/x = 2/3 → 2x = 24 → x = 12 cm.\n\n---\n\n**Problem 3 (Advanced):**\nA 5 m 60 cm high vertical pole casts a shadow 3 m 20 cm long. At the same time, a tower casts a shadow 12 m long. Find the height of the tower. (Hint: The sun's rays make equal angles, so the triangles are similar.)\n\n**Answer:** Height of pole = 5.6 m, Shadow = 3.2 m. Let tower height = h m. By similarity: h/5.6 = 12/3.2 = 3.75. h = 5.6 × 3.75 = 21 m. The tower is 21 m high."
                }
            ]
        },
        "d99d58775d420507": {
            "summary": "Similarity of triangles is established through specific criteria: AAA (or AA) similarity, SSS similarity, and SAS similarity. Two triangles are similar if their corresponding angles are equal (AA criterion) or their corresponding sides are in the same ratio (SSS criterion) or two sides are in proportion with the included angle equal (SAS criterion).",
            "chunks": [
                {
                    "title": "Similarity of Triangles",
                    "content": "Two triangles are **similar** if their corresponding angles are equal and their corresponding sides are in the same proportion. For triangles, checking all six conditions is often redundant because triangle similarity can be established using fewer conditions through specific criteria.\n\n**Basic Proportionality Theorem (Thales Theorem):**\nIf a line is drawn parallel to one side of a triangle intersecting the other two sides, then it divides those two sides in the same ratio.\n\nIn △ABC, if DE ∥ BC with D on AB and E on AC, then:\n   AD/DB = AE/EC\n\nConverse: If a line divides two sides of a triangle in the same ratio, then it is parallel to the third side.\n\n**Criteria for Similarity of Triangles:**\n\n**1. AAA (Angle-Angle-Angle) Similarity:**\n   If corresponding angles of two triangles are equal, the triangles are similar.\n   Since the sum of angles in a triangle is 180°, it is sufficient to check AA (two angles).\n\n**2. SSS (Side-Side-Side) Similarity:**\n   If the ratios of corresponding sides of two triangles are equal, the triangles are similar.\n   i.e., AB/DE = BC/EF = CA/FD\n\n**3. SAS (Side-Angle-Side) Similarity:**\n   If one angle of a triangle equals one angle of another triangle, and the sides including these angles are in proportion, the triangles are similar.\n   i.e., AB/DE = AC/DF and ∠A = ∠D"
                },
                {
                    "title": "Key Theorems and Properties of Similar Triangles",
                    "content": "**1. Basic Proportionality Theorem (Thales Theorem):**\n   Statement: If a line is drawn parallel to one side of a triangle, it divides the other two sides proportionally.\n   Application: Used to prove similarity and find unknown lengths.\n\n**2. AA Similarity Criterion:**\n   If two angles of one triangle are equal to two angles of another triangle, the triangles are similar.\n   Example: In △ABC and △DEF, if ∠A = ∠D and ∠B = ∠E, then △ABC ∼ △DEF.\n\n**3. SSS Similarity Criterion:**\n   If the three sides of one triangle are proportional to the three sides of another triangle, the triangles are similar.\n\n**4. SAS Similarity Criterion:**\n   If two sides are proportional and the included angle is equal, the triangles are similar.\n\n**5. Properties of Similar Triangles:**\n   - Ratio of corresponding sides = scale factor (k)\n   - Ratio of perimeters = k\n   - Ratio of areas = k²\n   - Ratio of corresponding medians = k\n   - Ratio of corresponding altitudes = k\n\n**6. Important Results:**\n   - In a right triangle, the altitude from the right angle to the hypotenuse creates two triangles similar to the original and to each other.\n   - The Pythagoras theorem can be proved using similarity of triangles.\n\n**7. Application:**\n   Used extensively in problems involving heights and distances, shadow problems, and geometric proofs."
                },
                {
                    "title": "Worked Example: Proving Triangle Similarity",
                    "content": "**Problem:** In △ABC, D and E are points on AB and AC respectively such that DE ∥ BC. If AD = 4 cm, DB = 6 cm, and AE = 5 cm, find EC.\n\n**Solution:**\n\n**Step 1:** Apply the Basic Proportionality Theorem.\nSince DE ∥ BC, by Thales theorem:\nAD/DB = AE/EC\n\n**Step 2:** Substitute known values.\n4/6 = 5/EC\n\n**Step 3:** Cross-multiply.\n4 × EC = 6 × 5\n4EC = 30\nEC = 7.5 cm\n\n**Step 4:** Verify.\nAD/DB = 4/6 = 2/3\nAE/EC = 5/7.5 = 50/75 = 2/3 ✓\n\n---\n\n**Problem 2:** Check if △ABC and △DEF are similar given:\nAB = 4 cm, BC = 6 cm, CA = 8 cm\nDE = 6 cm, EF = 9 cm, FD = 12 cm\n\n**Solution:**\nCheck SSS criterion:\nAB/DE = 4/6 = 2/3\nBC/EF = 6/9 = 2/3\nCA/FD = 8/12 = 2/3\n\nAll ratios are equal (2/3). Therefore, △ABC ∼ △DEF by SSS criterion."
                },
                {
                    "title": "Common Mistakes and Tips for Triangle Similarity",
                    "content": "**Common Mistakes:**\n\n❌ **Confusing similarity criteria with congruence criteria:** SSS similarity only requires proportional sides (not equal). SSS congruence requires equal sides.\n\n❌ **Wrong correspondence:** When checking similarity, ensure the correct vertices correspond. △ABC ∼ △DEF means A↔D, B↔E, C↔F.\n\n❌ **Applying Thales theorem incorrectly:** The parallel line must intersect the other TWO sides (not extensions).\n\n❌ **AAA vs AA:** AAA similarity says if all three angles are equal, triangles are similar. But since sum is always 180°, checking two angles is sufficient (AA criterion).\n\n**Tips and Tricks:**\n\n✓ **AA is easiest:** If you can show two angles are equal, the triangles are automatically similar. No need to check sides.\n\n✓ **Check SAS carefully:** The angle must be BETWEEN the two proportional sides, not any angle.\n\n✓ **Drawing helps:** Mark equal angles and proportional sides on the diagram to visualize the correspondence.\n\n✓ **Common angle pairs:** Vertically opposite angles, alternate angles (with parallel lines), corresponding angles, and common angles are often used to establish AA similarity."
                },
                {
                    "title": "Practice Problems on Triangle Similarity",
                    "content": "**Problem 1 (Basic):**\nIn △ABC, DE ∥ BC, AD = 3 cm, DB = 5 cm, AC = 12 cm. Find AE.\n\n**Answer:** By BPT, AD/DB = AE/EC. 3/5 = AE/(12-AE). 3(12-AE) = 5AE → 36 - 3AE = 5AE → 36 = 8AE → AE = 4.5 cm.\n\n---\n\n**Problem 2 (Intermediate):**\nProve that if in two triangles, corresponding angles are equal, then their corresponding sides are in proportion.\n\n**Answer:** Given △ABC and △DEF with ∠A=∠D, ∠B=∠E, ∠C=∠F. Construct points P on AB and Q on AC such that AP=DE and AQ=DF. Join PQ. By SAS congruence, △APQ ≅ △DEF. So ∠APQ=∠E=∠B. Therefore PQ ∥ BC (corresponding angles equal). By BPT, AP/PB = AQ/QC → DE/(AB-DE) = DF/(AC-DF). This leads to AB/DE = AC/DF. Similarly, BC/EF = AB/DE. Hence sides are proportional. △ABC ∼ △DEF.\n\n---\n\n**Problem 3 (Advanced):**\nA girl of height 90 cm is walking away from a lamp-post at a speed of 1.2 m/s. If the lamp-post is 3.6 m above the ground, find the length of her shadow after 4 seconds.\n\n**Answer:** Distance from lamp-post after 4s = 1.2×4 = 4.8 m. Let shadow length = x m. Height: girl = 0.9 m, lamp = 3.6 m. By similar triangles: x/(4.8+x) = 0.9/3.6 = 1/4. 4x = 4.8 + x → 3x = 4.8 → x = 1.6 m. Shadow length = 1.6 m."
                }
            ]
        },
        "ab3f38d401f700f9": {
            "summary": "The criteria for similarity of triangles — AA, SSS, and SAS — provide efficient ways to establish that two triangles are similar. These criteria are used extensively in geometric proofs and real-world applications. The AA criterion is most common; SSS requires checking three ratios; SAS combines both sides and angles.",
            "chunks": [
                {
                    "title": "Criteria for Similarity of Triangles",
                    "content": "Three main criteria establish similarity between triangles without checking all six conditions (3 angles + 3 sides):\n\n**1. AA (Angle-Angle) Similarity Criterion:**\n   If two angles of one triangle are equal to two angles of another triangle, the triangles are similar.\n   This is the most commonly used criterion because it requires the least information.\n\n**2. SSS (Side-Side-Side) Similarity Criterion:**\n   If the three sides of one triangle are proportional to the three sides of another triangle, the triangles are similar.\n   i.e., AB/DE = BC/EF = CA/FD\n\n**3. SAS (Side-Angle-Side) Similarity Criterion:**\n   If two sides of one triangle are proportional to two sides of another triangle, and the included angles are equal, the triangles are similar.\n   i.e., AB/DE = AC/DF and ∠A = ∠D\n\n**Important Distinction:**\n   - AAA (angle-angle-angle) is equivalent to AA (since sum of angles is 180°)\n   - AAA is a similarity criterion, NOT a congruence criterion\n   - AAA congruence does NOT exist (it gives similarity, not congruence)\n\n**Comparison with Congruence Criteria:**\n   - AA similarity ↔ no direct congruence equivalent (ASA/AAS are congruence)\n   - SSS similarity ↔ SSS congruence (but sides are proportional, not equal)\n   - SAS similarity ↔ SAS congruence (but sides are proportional, not equal)"
                },
                {
                    "title": "Using Similarity Criteria: Examples and Applications",
                    "content": "**1. AA Criterion in Action:**\n   Example: In △ABC and △DEF, ∠A = 50°, ∠B = 70°, ∠D = 50°, ∠E = 70°.\n   Since two angles match, by AA criterion, △ABC ∼ △DEF.\n   The third angles automatically match: ∠C = 180°-120° = 60° = ∠F.\n\n**2. SSS Criterion in Action:**\n   Example: △ABC has sides 3, 4, 5. △DEF has sides 6, 8, 10.\n   3/6 = 4/8 = 5/10 = 1/2 (all ratios equal).\n   By SSS criterion, △ABC ∼ △DEF. Scale factor = 1/2.\n\n**3. SAS Criterion in Action:**\n   Example: In △ABC and △DEF:\n   AB = 5, AC = 7, DE = 10, DF = 14, ∠A = ∠D = 60°.\n   AB/DE = 5/10 = 1/2, AC/DF = 7/14 = 1/2, ∠A = ∠D.\n   By SAS criterion, △ABC ∼ △DEF.\n\n**4. Applications:**\n   - Finding unknown lengths in geometric figures\n   - Proving geometric relationships\n   - Shadow and height measurement problems\n   - Map scaling and model building"
                },
                {
                    "title": "Worked Example: Applying Similarity Criteria",
                    "content": "**Problem:** Determine if △ABC and △PQR are similar in each case:\n(a) AB = 6 cm, BC = 8 cm, CA = 10 cm; PQ = 9 cm, QR = 12 cm, RP = 15 cm\n(b) ∠A = 45°, ∠B = 75°, ∠P = 45°, ∠Q = 60°\n\n**Solution:**\n\n**(a) Check SSS criterion:**\nAB/PQ = 6/9 = 2/3\nBC/QR = 8/12 = 2/3\nCA/RP = 10/15 = 2/3\nAll ratios = 2/3. By SSS criterion, △ABC ∼ △PQR ✓\n\n**(b) Check AA criterion:**\n∠A = 45° = ∠P ✓\n∠B = 75°, ∠Q = 60°\nBut wait — we need two pairs of equal angles. Let's find the third angles:\n∠C = 180° - 45° - 75° = 60°\n∠R = 180° - 45° - 60° = 75°\n\nSo ∠B = 75° = ∠R and ∠C = 60° = ∠Q.\nThus, by AA criterion, △ABC ∼ △PRQ (with correspondence A↔P, B↔R, C↔Q).\n\n---\n\n**Problem:** Are all right-angled isosceles triangles similar?\n**Answer:** Yes. Every right-angled isosceles triangle has angles 45°, 45°, 90°. By AA criterion (45° = 45° and 90° = 90°), any two such triangles are similar."
                },
                {
                    "title": "Common Mistakes and Tips for Similarity Criteria",
                    "content": "**Common Mistakes:**\n\n❌ **AAA vs AA confusion:** While we say AAA criterion, we only need to check two angles (AA). The third automatically follows.\n\n❌ **SSS similarity vs SSS congruence:** In SSS similarity, sides are PROPORTIONAL (not equal). A common error is to check for equality rather than proportion.\n\n❌ **SAS similarity requires included angle:** The equal angle must be BETWEEN the two proportional sides. If you have AB/DE = BC/EF and ∠B = ∠E, that's SAS. But if you have AB/DE = BC/EF and ∠A = ∠D, that's NOT valid SAS.\n\n❌ **Wrong correspondence:** When stating similarity, the order of vertices matters. △ABC ∼ △DEF means A↔D, B↔E, C↔F.\n\n**Tips and Tricks:**\n\n✓ **AA is usually fastest:** In most geometry problems, proving two angles equal is easier than checking three side ratios.\n\n✓ **Vertically opposite angles:** Often used in AA proofs — they are always equal.\n\n✓ **Common angle:** If two triangles share an angle, it provides one pair of equal angles for AA.\n\n✓ **Parallel lines:** Alternate interior and corresponding angles from parallel lines provide equal angles for AA proofs."
                },
                {
                    "title": "Practice Problems on Similarity Criteria",
                    "content": "**Problem 1 (Basic):**\nCheck similarity: △ABC with AB=4, BC=5, CA=6 and △DEF with DE=8, EF=10, FD=12.\n\n**Answer:** AB/DE=4/8=1/2, BC/EF=5/10=1/2, CA/FD=6/12=1/2. All ratios equal. △ABC ∼ △DEF by SSS.\n\n---\n\n**Problem 2 (Intermediate):**\nIn △ABC, ∠A = 60°, ∠B = 50°. In △DEF, ∠D = 60°, ∠F = 70°. Show that the triangles are similar.\n\n**Answer:** ∠C = 180°-110° = 70°. ∠E = 180°-130° = 50°. So ∠A=∠D=60°, ∠B=∠E=50°. By AA criterion, △ABC ∼ △DEF.\n\n---\n\n**Problem 3 (Advanced):**\nIn a trapezium ABCD, AB ∥ DC. Diagonals AC and BD intersect at O. Prove that AO/OC = BO/OD.\n\n**Answer:** In △AOB and △COD: ∠AOB = ∠COD (vertically opposite angles). ∠OAB = ∠OCD (alternate angles, since AB∥CD with transversal AC). By AA criterion, △AOB ∼ △COD. Therefore AO/OC = BO/OD (corresponding sides proportional)."
                }
            ]
        },
        "858538c9c7f376bc": {
            "summary": "The ratio of areas of two similar triangles equals the square of the ratio of their corresponding sides. If △ABC ∼ △DEF with scale factor k, then Area(△ABC)/Area(△DEF) = k² = (AB/DE)² = (BC/EF)² = (CA/FD)². This relationship is used to find areas, side lengths, and in various geometric proofs.",
            "chunks": [
                {
                    "title": "Areas of Similar Triangles",
                    "content": "The relationship between the areas of similar triangles is one of the most important results in geometry. It connects the concept of similarity with area measurement.\n\n**Theorem:** The ratio of the areas of two similar triangles is equal to the square of the ratio of their corresponding sides.\n\nIf △ABC ∼ △DEF with scale factor k = AB/DE = BC/EF = CA/FD, then:\n\n**Area(△ABC) / Area(△DEF) = k² = (AB/DE)² = (BC/EF)² = (CA/FD)²**\n\n**Proof idea:**\n   - Draw altitudes from corresponding vertices\n   - The altitudes are in the same ratio as the sides (proved using similarity of smaller triangles)\n   - Area = ½ × base × height\n   - Area ratio = (½×b₁×h₁)/(½×b₂×h₂) = (b₁/b₂)(h₁/h₂) = k × k = k²\n\n**Example:** If △ABC ∼ △PQR and AB:PQ = 2:3, then:\n   Area(△ABC)/Area(△PQR) = 4:9\n\n**Applications:**\n   - Finding areas when side ratios are known\n   - Finding side ratios when area ratios are known\n   - Solving problems involving maps and models\n   - Geometric proofs"
                },
                {
                    "title": "Properties and Applications of Area Ratios",
                    "content": "**1. Area Ratio Formula:**\n   If △ABC ∼ △DEF with scale factor k:\n   Area(△ABC)/Area(△DEF) = k²\n\n**2. Finding Side Ratio from Area Ratio:**\n   If area ratio = m:n, then side ratio = √m:√n\n\n**3. Relationship with Perimeters:**\n   - Perimeter ratio = k (scale factor)\n   - Area ratio = k²\n\n**4. Examples:**\n\n   **Example 1:** Two similar triangles have areas 36 cm² and 49 cm². Find the ratio of their corresponding sides.\n   Area ratio = 36/49\n   Side ratio = √(36/49) = 6/7\n\n   **Example 2:** △ABC ∼ △PQR. AB = 5 cm, PQ = 15 cm. Area of △ABC = 20 cm². Find area of △PQR.\n   Scale factor = AB/PQ = 5/15 = 1/3\n   Area ratio = (1/3)² = 1/9\n   Area(△PQR) = 9 × Area(△ABC) = 9 × 20 = 180 cm²\n\n**5. Important Note:**\n   The converse is also true: if the areas of two triangles are in the ratio of the squares of corresponding sides, the triangles are similar.\n\n**6. Practical Application:**\n   If the scale of a map is 1:10000, and a park on the map has area 5 cm², the actual area of the park is 5 × (10000)² = 5 × 10⁸ cm² = 5 hectares."
                },
                {
                    "title": "Worked Example: Area of Similar Triangles",
                    "content": "**Problem:** In △ABC ∼ △DEF, the area of △ABC is 121 cm² and the area of △DEF is 64 cm². If BC = 9.9 cm, find the length of the corresponding side EF.\n\n**Solution:**\n\n**Step 1:** Write the area ratio.\nArea(△ABC)/Area(△DEF) = 121/64\n\n**Step 2:** The area ratio equals the square of the side ratio.\n(BC/EF)² = 121/64\n\n**Step 3:** Take square root.\nBC/EF = √(121/64) = 11/8\n\n**Step 4:** Substitute BC = 9.9 cm.\n9.9/EF = 11/8\nEF = 9.9 × 8/11 = 79.2/11 = 7.2 cm\n\n**Step 5:** Verify.\nArea ratio = 121/64 = (11/8)²\nBC/EF = 9.9/7.2 = 99/72 = 11/8 ✓\n\n---\n\n**Problem 2:** The areas of two similar triangles are 81 cm² and 144 cm². If the perimeter of the smaller triangle is 27 cm, find the perimeter of the larger triangle.\n\n**Solution:**\nArea ratio = 81/144 = 9/16\nSide ratio = √(9/16) = 3/4 = perimeter ratio\nLet perimeter of larger = P: 27/P = 3/4 → P = 36 cm"
                },
                {
                    "title": "Common Mistakes and Tips for Areas of Similar Triangles",
                    "content": "**Common Mistakes:**\n\n❌ **Forgetting to square the ratio:** The area ratio is k², not k. If sides are in ratio 2:3, areas are in ratio 4:9, NOT 2:3.\n\n❌ **Taking square root incorrectly:** When going from area ratio to side ratio, take the square root. Side ratio = √(area ratio).\n\n❌ **Confusing perimeter and area ratios:** Perimeter ratio = k (scale factor). Area ratio = k². These are different!\n\n❌ **Using wrong correspondence:** Ensure the correct sides correspond before applying the area ratio.\n\n**Tips and Tricks:**\n\n✓ **Memory aid:** 'Area is squared, so the ratio is squared.' Side ratio = k, area ratio = k².\n\n✓ **Quick calculation:** If sides are in ratio m:n, areas are in ratio m²:n².\n\n✓ **Verification:** If the larger triangle has larger sides, its area should be proportionally larger (by the square of the scale factor).\n\n✓ **Units:** Area is in square units. If side ratio is 1:100, area ratio is 1:10000. Always check unit consistency."
                },
                {
                    "title": "Practice Problems on Areas of Similar Triangles",
                    "content": "**Problem 1 (Basic):**\n△ABC ∼ △XYZ. AB = 4 cm, XY = 12 cm. If area of △ABC is 20 cm², find area of △XYZ.\n\n**Answer:** Scale factor k = 4/12 = 1/3. Area ratio = k² = 1/9. Area(△XYZ) = 9 × 20 = 180 cm².\n\n---\n\n**Problem 2 (Intermediate):**\nThe corresponding medians of two similar triangles are in the ratio 4:7. Find the ratio of their areas.\n\n**Answer:** Medians are in the same ratio as corresponding sides. So side ratio = 4:7. Area ratio = 4²:7² = 16:49.\n\n---\n\n**Problem 3 (Advanced):**\n△ABC ∼ △PQR. AD is a median of △ABC and PM is a median of △PQR. Prove that Area(△ABC)/Area(△PQR) = AD²/PM².\n\n**Answer:** Since △ABC ∼ △PQR, AB/PQ = BC/QR = CA/RP = k. Also AD/PM = k (medians are in the same ratio as sides). Area(△ABC)/Area(△PQR) = k² = (AD/PM)² = AD²/PM². Hence proved."
                }
            ]
        },
        "19a051d6510e2494": {
            "summary": "The Pythagoras theorem states that in a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides: a² + b² = c². Its converse states that if a² + b² = c², the triangle is right-angled. The theorem is proved using similarity of triangles and is fundamental to geometry, trigonometry, and real-world measurements.",
            "chunks": [
                {
                    "title": "Pythagoras Theorem",
                    "content": "The **Pythagoras Theorem** is one of the most famous and widely used results in mathematics. It relates the sides of a right-angled triangle.\n\n**Statement:** In a right-angled triangle, the square of the hypotenuse (the side opposite the right angle) is equal to the sum of the squares of the other two sides.\n\nIf △ABC is right-angled at B, then:\n**AC² = AB² + BC²**\n\n**Named after:** The ancient Greek mathematician **Pythagoras** (c. 570-495 BCE), though the result was known to Babylonian and Indian mathematicians earlier. In India, it was known as the **Baudhayana theorem** (c. 800 BCE).\n\n**Proof using Similarity:**\n   - Draw BD ⟂ AC (altitude from right angle to hypotenuse)\n   - This creates two smaller triangles, ABD and BDC\n   - △ABC ∼ △ABD ∼ △BDC (by AA similarity)\n   - From △ABC ∼ △ABD: AB/AD = AC/AB → AB² = AC × AD\n   - From △ABC ∼ △BDC: BC/DC = AC/BC → BC² = AC × DC\n   - Adding: AB² + BC² = AC(AD + DC) = AC × AC = AC²\n\nThis proof shows the deep connection between similarity and the Pythagoras theorem."
                },
                {
                    "title": "Key Results and Applications of Pythagoras Theorem",
                    "content": "**1. Standard Form:**\n   In a right triangle with legs a, b and hypotenuse c:\n   a² + b² = c²\n   c = √(a² + b²)\n\n**2. Converse of Pythagoras Theorem:**\n   If in a triangle, the square of one side equals the sum of squares of the other two sides, then the triangle is right-angled with the right angle opposite the longest side.\n   If a² + b² = c², then the angle opposite side c is 90°.\n\n**3. Pythagorean Triplets:**\n   Sets of three positive integers satisfying a² + b² = c²:\n   - (3, 4, 5): 3²+4² = 9+16 = 25 = 5²\n   - (5, 12, 13): 5²+12² = 25+144 = 169 = 13²\n   - (7, 24, 25): 7²+24² = 49+576 = 625 = 25²\n   - (8, 15, 17): 8²+15² = 64+225 = 289 = 17²\n   - (9, 40, 41): 9²+40² = 81+1600 = 1681 = 41²\n\n   Any multiple of a Pythagorean triplet is also a triplet.\n   3k, 4k, 5k: e.g., (6, 8, 10), (9, 12, 15), (12, 16, 20)\n\n**4. Applications:**\n   - Finding distances (shortest distance, diagonal of rectangle)\n   - Height and distance problems\n   - Navigation and surveying\n   - Construction and architecture\n   - Coordinate geometry (distance formula)"
                },
                {
                    "title": "Worked Example: Applying Pythagoras Theorem",
                    "content": "**Problem:** A ladder 25 m long reaches a window 24 m above the ground. Find the distance of the foot of the ladder from the base of the wall.\n\n**Solution:**\n\n**Step 1:** Draw a right triangle.\nLet AB = height of window = 24 m (vertical wall)\nAC = length of ladder = 25 m (hypotenuse)\nBC = distance from wall = x (horizontal ground)\n\n**Step 2:** Apply Pythagoras theorem.\nAC² = AB² + BC²\n25² = 24² + x²\n\n**Step 3:** Solve for x.\n625 = 576 + x²\nx² = 625 - 576 = 49\nx = √49 = 7 m\n\n**Step 4:** Verify.\n24² + 7² = 576 + 49 = 625 = 25² ✓\n\nTherefore, the foot of the ladder is **7 m** from the wall.\n\n---\n\n**Problem 2:** Determine if a triangle with sides 9 cm, 40 cm, and 41 cm is right-angled.\n\n**Solution:**\nCheck the converse: Check if 41² = 9² + 40²\n9² + 40² = 81 + 1600 = 1681\n41² = 1681\nSince 9² + 40² = 41², the triangle is **right-angled** with hypotenuse 41 cm."
                },
                {
                    "title": "Common Mistakes and Tips for Pythagoras Theorem",
                    "content": "**Common Mistakes:**\n\n❌ **Wrong side as hypotenuse:** The hypotenuse is always the side opposite the right angle — the longest side. Don't assume the vertical side is always the hypotenuse.\n\n❌ **Forgetting the square root:** a² + b² = c² → c = √(a² + b²). Taking the square root is the final step, not c = a² + b².\n\n❌ **Applying to non-right triangles:** Pythagoras theorem ONLY applies to right-angled triangles. For other triangles, use the cosine rule.\n\n❌ **Sign errors:** The theorem is a² + b² = c². If 9² + 12² = c², then c² = 81+144 = 225, c = 15. If a² + 12² = 13², then a² = 169-144 = 25, a = 5.\n\n**Tips and Tricks:**\n\n✓ **Shortcuts with triplets:** Memorize common Pythagorean triplets (3-4-5, 5-12-13, 8-15-17, 7-24-25). If you recognize a multiple, you can find sides instantly.\n\n✓ **Check if triangle is right:** Use the converse: if a² + b² = c² for the longest side c, the triangle is right-angled.\n\n✓ **Diagonal of a rectangle:** d = √(l² + w²). This is a common application.\n\n✓ **Distance formula:** The distance between (x₁,y₁) and (x₂,y₂) = √[(x₂-x₁)²+(y₂-y₁)²] — derived from Pythagoras theorem."
                },
                {
                    "title": "Practice Problems on Pythagoras Theorem",
                    "content": "**Problem 1 (Basic):**\nFind the hypotenuse of a right triangle with legs 6 cm and 8 cm.\n\n**Answer:** c = √(6²+8²) = √(36+64) = √100 = 10 cm.\n\n---\n\n**Problem 2 (Intermediate):**\nA tree breaks due to storm and the broken part bends so that the top touches the ground making an angle of 30° with it. The distance from the foot of the tree to the point where the top touches the ground is 8 m. Find the height of the tree.\n\n**Answer:** Let the broken part = AC and standing part = AB. In right △ABC, AB/BC = tan 30° = 1/√3. BC = 8, so AB = 8/√3 m. AC/BC = sec 30° = 2/√3, so AC = 16/√3 m. Total height = AB + AC = 8/√3 + 16/√3 = 24/√3 = 8√3 m.\n\n---\n\n**Problem 3 (Advanced):**\nBl and CM are medians of △ABC right-angled at A. Prove that 4(BL² + CM²) = 5BC².\n\n**Answer:** In right △ABC, BC² = AB² + AC². BL² = AB² + (AC/2)² = AB² + AC²/4. CM² = AC² + (AB/2)² = AC² + AB²/4. BL² + CM² = AB²+AC²/4+AC²+AB²/4 = (5/4)(AB²+AC²) = (5/4)BC². Therefore, 4(BL²+CM²) = 5BC²."
                }
            ]
        }
    }

def math_ch7_10():
    return {}
def math_ch11_15():
    return {}
def science_ch1_4():
    return {}
def science_ch5_8():
    return {}
def science_ch9_13():
    return {}


if __name__ == "__main__":
    write_json("math_ch4.json", math_ch4())
    write_json("math_ch5.json", math_ch5())
